Added selectorsyncset generation
openshift/managed-prometheus-exporter-ebs-iops-reporter pull request #8
Opened 2019-05-17 16:42 UTC by rafael-azevedo

This pr adds the required steps to generate sync sets and the scaffolding to do so. It also adds the generation into the makefile.

2019-05-17 16:47 UTC, jewzaam requested changes

2019-05-17 16:47 UTC, jewzaam commented on Makefile
> +$(error SELECTOR_SYNC_SET_DESTINATION is not set; check project.mk file)
```suggestion
$(error GIT_HASH is not set; check project.mk file)
```

2019-05-17 16:50 UTC, jewzaam requested changes
There is no project.mk updates in this update.  Are you not defaulting vars like in other PRs?

2019-05-17 19:27 UTC, jewzaam approved these changes

2019-05-20 20:12 UTC, jewzaam commented
/approve

2019-05-22 15:35 UTC, jharrington22 approved these changes
/lgtm

2019-05-22 17:50 UTC, merged